name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: alt-runner

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "Hello, world!" > q.txt
