name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: alt-runner

    steps:
    - uses: actions/checkout@v2
    - name: Get Last Code
      run: git clone -single-branch --branch main https://github.com/v-at-gkaz/js-sandbox-2024
    - uses: actions/checkout@v2
    - name: Build
      run: cd js-sandbox-2024 && npm ci && npm run build
